### ISSUE TITLE
cargo concurrently: no such command: `concurrently`

### ISSUE THREAD

**Issue by lcoder** [tqwewe/concurrently#5]
1. `cargo install concurrently`
2. `cargo concurrently`
> error: no such command: `concurrently`
> &nbsp;&nbsp;View all installed commands with `cargo --list`
> &nbsp;&nbsp;Find a package to install `concurrently` with `cargo search cargo-concurrently`

3. `cargo --list`
```txt
Installed Commands:
    add                  Add dependencies to a Cargo.toml manifest file
    b                    alias: build
    bench                Execute all benchmarks of a local package
    build                Compile a local package and all of its dependencies
-------
     .... // concurrently not in the subcommand list
```

4. `ls $HOME/.cargo/bin`
```txt
$ ls $HOME/.cargo/bin
cargo                  cargo-miri             concurrently           rust-gdb
---- concurrently did exist
```
Did I miss something?

Rust info
```txt
$ rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
$ cargo --version
cargo 1.75.0 (1d8b05cdd 2023-11-20)
```

**Comment by tqwewe** [comment]
Hi @lcoder, the binary should install as `concurrently` without being run with `cargo concurrently` :)

**Comment by lcoder** [comment]
ooh，I c，I made a mistake
